import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import type { ExplanationResult } from "../types";

export function ExplanationPanel({ explanation }: { explanation: ExplanationResult }) {
  const maxAbs = Math.max(...explanation.top_factors.map((f) => Math.abs(f.contribution)), 0.001);

  return (
    <div className="space-y-5">
      <div className="glass-panel rounded-2xl p-4">
        <p className="text-xs text-[var(--text-muted)] mb-1">Plain-language summary</p>
        <p className="text-sm text-[var(--text-primary)]">{explanation.plain_language_summary}</p>
      </div>

      <div>
        <p className="text-xs font-medium text-[var(--text-muted)] uppercase tracking-wide mb-3">
          Top contributing factors
        </p>
        <div className="space-y-3">
          {explanation.top_factors.map((factor) => {
            const isUp = factor.direction === "increases_risk";
            const widthPct = (Math.abs(factor.contribution) / maxAbs) * 100;
            return (
              <div key={factor.feature}>
                <div className="flex items-center justify-between text-xs mb-1">
                  <span className="flex items-center gap-1 font-medium text-[var(--text-primary)]">
                    {isUp ? (
                      <ArrowUpRight className="h-3.5 w-3.5 text-rose-500" />
                    ) : (
                      <ArrowDownRight className="h-3.5 w-3.5 text-emerald-500" />
                    )}
                    {factor.feature.replace(/_/g, " ")}
                  </span>
                  <span className="text-[var(--text-muted)]">{factor.value.toFixed(2)}</span>
                </div>
                <div className="h-2 rounded-full bg-white/10 overflow-hidden">
                  <div
                    className="h-full rounded-full"
                    style={{
                      width: `${widthPct}%`,
                      background: isUp ? "#d03b3b" : "#0ca30c",
                    }}
                  />
                </div>
                <p className="text-xs text-[var(--text-secondary)] mt-1">{factor.explanation}</p>
              </div>
            );
          })}
        </div>
      </div>

      <p className="text-[11px] text-[var(--text-muted)] border-t border-white/10 pt-3">
        Generated by a from-scratch LIME-style local surrogate explainer (model: {explanation.model_name}) — perturbs
        the instance, fits a locally-weighted linear model, and reports each feature's local contribution.
      </p>
    </div>
  );
}
